---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: report-str
  name: report-str
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-app
      version: blue
  template:
    metadata:
      name: report-str-pod
      labels:
        app: report-app
        version: blue
    spec:
      containers:
      - name: report-str-container
        image: sachinjp/report-str:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8506
---
apiVersion: v1
kind: Service 
metadata:
  namespace: report-str
  name: report-str-svc
  labels:
    app: report-str-app
spec:
  selector:
    app: report-str-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 32224
    port: 80
    targetPort: 8506
